"""Add Genre model and relationship to Book

Revision ID: 6ff93ddcb6e1
Revises: 2c4d524a4b81
Create Date: 2024-07-26 13:59:25.119874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff93ddcb6e1'
down_revision: Union[str, None] = '2c4d524a4b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)

    # Add genre_id column to books table
    op.create_table('new_books',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('author', sa.String(), nullable=True),
                    sa.Column('year', sa.Integer(), nullable=True),
                    sa.Column('pages', sa.Integer(), nullable=True),
                    sa.Column('genre_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_new_books_id'), 'new_books', ['id'], unique=False)

    # Copy data from the old books table to the new one
    op.execute(
        'INSERT INTO new_books (id, title, author, year, pages) SELECT id, title, author, year, pages FROM books')

    # Drop the old books table
    op.drop_table('books')

    # Rename the new books table to books
    op.rename_table('new_books', 'books')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_books',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('author', sa.String(), nullable=True),
                    sa.Column('year', sa.Integer(), nullable=True),
                    sa.Column('pages', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_new_books_id'), 'new_books', ['id'], unique=False)

    # Copy data from the current books table to the new one
    op.execute(
        'INSERT INTO new_books (id, title, author, year, pages) SELECT id, title, author, year, pages FROM books')

    # Drop the current books table
    op.drop_table('books')

    # Rename the new books table to books
    op.rename_table('new_books', 'books')

    # Drop genres table
    op.drop_table('genres')
    # ### end Alembic commands ###
